# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: starlabio/docker-cargo-static:1

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Cargo Build
      run: cargo build --release --target x86_64-unknown-linux-musl
      
  artifact_upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/upload-artifact@v2.1.4
        with:
          name: add-user-to-sudoers
          if-no-files-found: error
          path: |
            target/x86_64-unknown-linux-musl/release/add_user_to_sudoers
            startup_script
